//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelCatalogue.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JewelCatalogue.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_to_database_icon {
            get {
                object obj = ResourceManager.GetObject("add-to-database-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_edit_icon {
            get {
                object obj = ResourceManager.GetObject("application-edit-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for Thumbnails.
        /// </summary>
        internal static string BaseFormControl_CellMouseMove_Click_here_for_Thumbnails {
            get {
                return ResourceManager.GetString("BaseFormControl_CellMouseMove_Click_here_for_Thumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to cancel order?.
        /// </summary>
        internal static string BaseFormControl_CloseOrderForm_Are_you_sure_want_to_cancel_order_ {
            get {
                return ResourceManager.GetString("BaseFormControl_CloseOrderForm_Are_you_sure_want_to_cancel_order_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Foo {
            get {
                object obj = ResourceManager.GetObject("Foo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid range of Weight !.
        /// </summary>
        internal static string frmAdvancesearch_button2_Click_Please_enter_valid_range_of_Weight__ {
            get {
                return ResourceManager.GetString("frmAdvancesearch_button2_Click_Please_enter_valid_range_of_Weight__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is already deselected.
        /// </summary>
        internal static string frmAllCatalogueProduct_btnDeselectAll_Click_It_is_already_deselected {
            get {
                return ResourceManager.GetString("frmAllCatalogueProduct_btnDeselectAll_Click_It_is_already_deselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewel Order Report.
        /// </summary>
        internal static string frmAllCatalogueProduct_btnProcess_Click_Jewel_Order_Report {
            get {
                return ResourceManager.GetString("frmAllCatalogueProduct_btnProcess_Click_Jewel_Order_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Customer Name for Excel Process..
        /// </summary>
        internal static string frmAllCatalogueProduct_btnProcess_Click_Please_enter_Customer_Name_for_Excel_Process_ {
            get {
                return ResourceManager.GetString("frmAllCatalogueProduct_btnProcess_Click_Please_enter_Customer_Name_for_Excel_Proc" +
                        "ess_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Jewelno for Excel Process..
        /// </summary>
        internal static string frmAllCatalogueProduct_btnProcess_Click_Please_select_Jewelno_for_Excel_Process_ {
            get {
                return ResourceManager.GetString("frmAllCatalogueProduct_btnProcess_Click_Please_select_Jewelno_for_Excel_Process_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Product(s) on Selected Page = .
        /// </summary>
        internal static string frmAllCatalogueProduct_frmAllCatalogueProduct_Load_ {
            get {
                return ResourceManager.GetString("frmAllCatalogueProduct_frmAllCatalogueProduct_Load_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record(s) Not found !.
        /// </summary>
        internal static string frmAllCatalogueProduct_frmAllCatalogueProduct_Load_Record_s__Not_found__ {
            get {
                return ResourceManager.GetString("frmAllCatalogueProduct_frmAllCatalogueProduct_Load_Record_s__Not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is already deselected.
        /// </summary>
        internal static string frmAllJewelsBarcodePrint_btnDeselectAll_Click_It_is_already_deselected {
            get {
                return ResourceManager.GetString("frmAllJewelsBarcodePrint_btnDeselectAll_Click_It_is_already_deselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Jewel selected for report!.
        /// </summary>
        internal static string frmAllJewelsBarcodePrint_btnGenerateBarcode_Click_No_Jewel_selected_for_report_ {
            get {
                return ResourceManager.GetString("frmAllJewelsBarcodePrint_btnGenerateBarcode_Click_No_Jewel_selected_for_report_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Last Page!.
        /// </summary>
        internal static string frmAllJewelsBarcodePrint_btnNext_Click_This_is_the_Last_Page_ {
            get {
                return ResourceManager.GetString("frmAllJewelsBarcodePrint_btnNext_Click_This_is_the_Last_Page_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the First Page!.
        /// </summary>
        internal static string frmAllJewelsBarcodePrint_btnPrevious_Click_This_is_the_First_Page_ {
            get {
                return ResourceManager.GetString("frmAllJewelsBarcodePrint_btnPrevious_Click_This_is_the_First_Page_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such PageNo eixsts! Please select different Page No.
        /// </summary>
        internal static string frmAllJewelsBarcodePrint_cmbPageNos_SelectedIndexChanged_No_such_PageNo_eixsts__Please_select_different_Page_No {
            get {
                return ResourceManager.GetString("frmAllJewelsBarcodePrint_cmbPageNos_SelectedIndexChanged_No_such_PageNo_eixsts__P" +
                        "lease_select_different_Page_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Jewel(s) on Selected Page = .
        /// </summary>
        internal static string frmAllJewelsBarcodePrint_dgvJewel_CellContentClick_ {
            get {
                return ResourceManager.GetString("frmAllJewelsBarcodePrint_dgvJewel_CellContentClick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Not found !.
        /// </summary>
        internal static string frmAllJewelsBarcodePrint_FillGrid_Records_Not_found__ {
            get {
                return ResourceManager.GetString("frmAllJewelsBarcodePrint_FillGrid_Records_Not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewel Order Report.
        /// </summary>
        internal static string frmBarCodeOrder_btnProcess_Click_Jewel_Order_Report {
            get {
                return ResourceManager.GetString("frmBarCodeOrder_btnProcess_Click_Jewel_Order_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Customer Name for Excel Process..
        /// </summary>
        internal static string frmBarCodeOrder_btnProcess_Click_Please_enter_Customer_Name_for_Excel_Process_ {
            get {
                return ResourceManager.GetString("frmBarCodeOrder_btnProcess_Click_Please_enter_Customer_Name_for_Excel_Process_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Jewelno for Excel Process..
        /// </summary>
        internal static string frmBarCodeOrder_btnProcess_Click_Please_select_Jewelno_for_Excel_Process_ {
            get {
                return ResourceManager.GetString("frmBarCodeOrder_btnProcess_Click_Please_select_Jewelno_for_Excel_Process_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  already exists!Please search for new record .
        /// </summary>
        internal static string frmBarCodeOrder_FindJewel__already_exists_Please_search_for_new_record_ {
            get {
                return ResourceManager.GetString("frmBarCodeOrder_FindJewel__already_exists_Please_search_for_new_record_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Not found !.
        /// </summary>
        internal static string frmBarCodeOrder_FindJewel_Records_Not_found__ {
            get {
                return ResourceManager.GetString("frmBarCodeOrder_FindJewel_Records_Not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewel Order Report.
        /// </summary>
        internal static string frmCatalogue_btnProcess_Click_Jewel_Order_Report {
            get {
                return ResourceManager.GetString("frmCatalogue_btnProcess_Click_Jewel_Order_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records to Process..
        /// </summary>
        internal static string frmCatalogue_btnProcess_Click_No_Records_to_Process_ {
            get {
                return ResourceManager.GetString("frmCatalogue_btnProcess_Click_No_Records_to_Process_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Customer Name for Excel Process..
        /// </summary>
        internal static string frmCatalogue_btnProcess_Click_Please_enter_Customer_Name_for_Excel_Process_ {
            get {
                return ResourceManager.GetString("frmCatalogue_btnProcess_Click_Please_enter_Customer_Name_for_Excel_Process_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid range of Weight and select Jewel Description!.
        /// </summary>
        internal static string frmCatalogue_SelectWeight_Please_enter_valid_range_of_Weight_and_select_Jewel_Description_ {
            get {
                return ResourceManager.GetString("frmCatalogue_SelectWeight_Please_enter_valid_range_of_Weight_and_select_Jewel_Des" +
                        "cription_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one Jewel Description.
        /// </summary>
        internal static string frmCatalogue_SelectWeight_Please_select_atleast_one_Jewel_Description {
            get {
                return ResourceManager.GetString("frmCatalogue_SelectWeight_Please_select_atleast_one_Jewel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Exit?.
        /// </summary>
        internal static string frmDataEntry_frmDataEntry_FormClosing_Are_you_sure_you_want_to_Exit_ {
            get {
                return ResourceManager.GetString("frmDataEntry_frmDataEntry_FormClosing_Are_you_sure_you_want_to_Exit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t saved your data..
        /// </summary>
        internal static string frmDataEntry_frmDataEntry_FormClosing_You_haven_t_saved_your_data_ {
            get {
                return ResourceManager.GetString("frmDataEntry_frmDataEntry_FormClosing_You_haven_t_saved_your_data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Graphics Types|*.jpg;|JPG|*.jpg;.
        /// </summary>
        internal static string frmJewelMaster_BindForm_All_Graphics_Types___jpg__JPG___jpg_ {
            get {
                return ResourceManager.GetString("frmJewelMaster_BindForm_All_Graphics_Types___jpg__JPG___jpg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file to upload..
        /// </summary>
        internal static string frmJewelMaster_btnSave_Click_Please_select_file_to_upload_ {
            get {
                return ResourceManager.GetString("frmJewelMaster_btnSave_Click_Please_select_file_to_upload_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select proper dia Wt..
        /// </summary>
        internal static string frmJewelMaster_btnSave_Click_Please_select_proper_dia_Wt_ {
            get {
                return ResourceManager.GetString("frmJewelMaster_btnSave_Click_Please_select_proper_dia_Wt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select proper grs Wt..
        /// </summary>
        internal static string frmJewelMaster_btnSave_Click_Please_select_proper_grs_Wt_ {
            get {
                return ResourceManager.GetString("frmJewelMaster_btnSave_Click_Please_select_proper_grs_Wt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select proper net Wt..
        /// </summary>
        internal static string frmJewelMaster_btnSave_Click_Please_select_proper_net_Wt_ {
            get {
                return ResourceManager.GetString("frmJewelMaster_btnSave_Click_Please_select_proper_net_Wt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to exit ?.
        /// </summary>
        internal static string frmMDIParent__terminate_Are_you_sure_want_to_exit__ {
            get {
                return ResourceManager.GetString("frmMDIParent__terminate_Are_you_sure_want_to_exit__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        internal static string frmMDIParent__terminate_Exit_Application {
            get {
                return ResourceManager.GetString("frmMDIParent__terminate_Exit_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete jewel record..
        /// </summary>
        internal static string frmMDIParent_deleteToolStripButton_Click_Are_you_sure_want_to_delete_jewel_record_ {
            get {
                return ResourceManager.GetString("frmMDIParent_deleteToolStripButton_Click_Are_you_sure_want_to_delete_jewel_record" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Directory path not set !, please set it from Tools -&gt; App Settings !.
        /// </summary>
        internal static string frmMDIParent_frmMDIParent_Load_Image_Directory_path_not_set____please_set_it_from_Tools____App_Settings__ {
            get {
                return ResourceManager.GetString("frmMDIParent_frmMDIParent_Load_Image_Directory_path_not_set____please_set_it_from" +
                        "_Tools____App_Settings__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Directory path not set !, please click ok to set it now..
        /// </summary>
        internal static string frmMDIParent_manageJewelsToolStripMenuItem_Click_Image_Directory_path_not_set____please_click_ok_to_set_it_now_ {
            get {
                return ResourceManager.GetString("frmMDIParent_manageJewelsToolStripMenuItem_Click_Image_Directory_path_not_set____" +
                        "please_click_ok_to_set_it_now_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the Last Page!.
        /// </summary>
        internal static string frmProduct_btnNext_Click_This_is_the_Last_Page_ {
            get {
                return ResourceManager.GetString("frmProduct_btnNext_Click_This_is_the_Last_Page_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the First Page!.
        /// </summary>
        internal static string frmProduct_btnPrevious_Click_This_is_the_First_Page_ {
            get {
                return ResourceManager.GetString("frmProduct_btnPrevious_Click_This_is_the_First_Page_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such PageNo eixsts! Please select different Page No.
        /// </summary>
        internal static string frmProduct_cmbPageNos_SelectedIndexChanged_No_such_PageNo_eixsts__Please_select_different_Page_No {
            get {
                return ResourceManager.GetString("frmProduct_cmbPageNos_SelectedIndexChanged_No_such_PageNo_eixsts__Please_select_d" +
                        "ifferent_Page_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already exists!.
        /// </summary>
        internal static string frmProduct_dgvJewel_CellContentClick_Record_already_exists_ {
            get {
                return ResourceManager.GetString("frmProduct_dgvJewel_CellContentClick_Record_already_exists_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Product(s) on Selected Page = .
        /// </summary>
        internal static string frmProduct_FillGrid_ {
            get {
                return ResourceManager.GetString("frmProduct_FillGrid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Not found !.
        /// </summary>
        internal static string frmProduct_FillGrid_Records_Not_found__ {
            get {
                return ResourceManager.GetString("frmProduct_FillGrid_Records_Not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Folder Path Not Found.
        /// </summary>
        internal static string frmSettings_btnSave_Click_Error___Folder_Path_Not_Found {
            get {
                return ResourceManager.GetString("frmSettings_btnSave_Click_Error___Folder_Path_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter proper folder path.
        /// </summary>
        internal static string frmSettings_btnSave_Click_Please_enter_proper_folder_path {
            get {
                return ResourceManager.GetString("frmSettings_btnSave_Click_Please_enter_proper_folder_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HGHGGG_232013_14_44_14 {
            get {
                object obj = ResourceManager.GetObject("HGHGGG-232013_14_44_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HHHH_232013_15_00_20 {
            get {
                object obj = ResourceManager.GetObject("HHHH-232013_15_00_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hide_left_icon {
            get {
                object obj = ResourceManager.GetObject("hide-left-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hide_right_icon {
            get {
                object obj = ResourceManager.GetObject("hide-right-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JewelLogo {
            get {
                object obj = ResourceManager.GetObject("JewelLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Misc_Delete_Database_icon {
            get {
                object obj = ResourceManager.GetObject("Misc-Delete-Database-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navigate_left_icon {
            get {
                object obj = ResourceManager.GetObject("navigate-left-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navigate_right_icon {
            get {
                object obj = ResourceManager.GetObject("navigate-right-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Print1 {
            get {
                object obj = ResourceManager.GetObject("Print1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection could not be established, please check connection file..
        /// </summary>
        internal static string Program_Main_Connection_could_not_be_established__please_check_connection_file_ {
            get {
                return ResourceManager.GetString("Program_Main_Connection_could_not_be_established__please_check_connection_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software demo period is over, Please contact vendor.
        /// </summary>
        internal static string Program_Main_Your_software_demo_period_is_over__Please_contact_vendor {
            get {
                return ResourceManager.GetString("Program_Main_Your_software_demo_period_is_over__Please_contact_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_icon {
            get {
                object obj = ResourceManager.GetObject("refresh-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TirthJewels {
            get {
                object obj = ResourceManager.GetObject("TirthJewels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
