//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using JetCoders.Shared;

namespace Connections
{
    [Serializable]
    public partial class Address : IEntityBase
    {
        #region Primitive Properties
    
        public virtual int AddressId
        {
            get;
            set;
        }
    
        public virtual string AddressLine1
        {
            get;
            set;
        }
    
        public virtual string AddressLine2
        {
            get;
            set;
        }
    
        public virtual string City
        {
            get;
            set;
        }
    
        public virtual string PostalCode
        {
            get;
            set;
        }
    
        public virtual string State
        {
            get;
            set;
        }
    
        public virtual string Country
        {
            get;
            set;
        }
    
        public virtual string Phone
        {
            get;
            set;
        }
    
        public virtual string Fax
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Customer Customers
        {
            get { return _customers; }
            set
            {
                if (!ReferenceEquals(_customers, value))
                {
                    var previousValue = _customers;
                    _customers = value;
                    FixupCustomers(previousValue);
                }
            }
        }
        private Customer _customers;
    
        public virtual Supplier Suppliers
        {
            get { return _suppliers; }
            set
            {
                if (!ReferenceEquals(_suppliers, value))
                {
                    var previousValue = _suppliers;
                    _suppliers = value;
                    FixupSuppliers(previousValue);
                }
            }
        }
        private Supplier _suppliers;
    
        public virtual User Users
        {
            get { return _users; }
            set
            {
                if (!ReferenceEquals(_users, value))
                {
                    var previousValue = _users;
                    _users = value;
                    FixupUsers(previousValue);
                }
            }
        }
        private User _users;

        #endregion

        #region Association Fixup
    
        private void FixupCustomers(Customer previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Address, this))
            {
                previousValue.Address = null;
            }
    
            if (Customers != null)
            {
                Customers.Address = this;
            }
        }
    
        private void FixupSuppliers(Supplier previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Address, this))
            {
                previousValue.Address = null;
            }
    
            if (Suppliers != null)
            {
                Suppliers.Address = this;
            }
        }
    
        private void FixupUsers(User previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Address, this))
            {
                previousValue.Address = null;
            }
    
            if (Users != null)
            {
                Users.Address = this;
            }
        }

        #endregion

    }
}
