//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using JetCoders.Shared;

namespace Connections
{
    [Serializable]
    public partial class ConfigurationMaster : IEntityBase
    {
        #region Primitive Properties
    
        public virtual int ConfigurationId
        {
            get;
            set;
        }
    
        public virtual string Particulars
        {
            get;
            set;
        }
    
        public virtual string ConfigurationValue
        {
            get;
            set;
        }
    
    	public ProductCategory ProductCategory
    	{
    		get { return (ProductCategory) ProductCategory_Enum; }
    		set { ProductCategory_Enum = (short) value; }
    	}
        public virtual short ProductCategory_Enum
        {
            get;
            set;
        }
    
        public virtual string Remarks
        {
            get;
            set;
        }
    
        public virtual bool Active
        {
            get;
            set;
        }
    
    	public JewelItemCategory JewelItemCategory
    	{
    		get { return (JewelItemCategory) JewelItemCategory_Enum; }
    		set { JewelItemCategory_Enum = (short) value; }
    	}
        public virtual short JewelItemCategory_Enum
        {
            get;
            set;
        }
    
        public virtual System.DateTime AccessedDate
        {
            get;
            set;
        }
    
        public virtual int AccessedBy
        {
            get;
            set;
        }

        #endregion

    }
}
