//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using JetCoders.Shared;

namespace Connections
{
    [Serializable]
    public partial class Customer : IEntityBase
    {
        #region Primitive Properties
    
        public virtual int CustomersId
        {
            get;
            set;
        }
    
        public virtual string CustomersCode
        {
            get;
            set;
        }
    
        public virtual string CompanyName
        {
            get;
            set;
        }
    
        public virtual string ContactName
        {
            get;
            set;
        }
    
    	public CustomesStatus CustomesStatus
    	{
    		get { return (CustomesStatus) CustomesStatus_Enum; }
    		set { CustomesStatus_Enum = (short) value; }
    	}
        public virtual short CustomesStatus_Enum
        {
            get;
            set;
        }
    
    
    	private CustomerProperties _properties = null;
    	
    	public virtual CustomerProperties Properties
    	{
    		get 
    		{
    			if ( _properties == null )
    				_properties = new CustomerProperties();
    				
    			return _properties;
    		}
    		
    		set { _properties = value; }
    	}
        private string CustomerProperties_Xml
        {
    		get { return this.Properties.Serialize<CustomerProperties>().ToString(); }
    		set { this.Properties = DataContractHelper.Deserialize<CustomerProperties>(value); }
        }
    
        public virtual string VATNumber
        {
            get;
            set;
        }
    
        public virtual string CSTNumber
        {
            get;
            set;
        }
    
        public virtual string PANNumber
        {
            get;
            set;
        }
    
        public virtual System.DateTime AccessedDate
        {
            get;
            set;
        }
    
        public virtual int AccessedBy
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Address Address
        {
            get { return _address; }
            set
            {
                if (!ReferenceEquals(_address, value))
                {
                    var previousValue = _address;
                    _address = value;
                    FixupAddress(previousValue);
                }
            }
        }
        private Address _address;

        #endregion

        #region Association Fixup
    
        private void FixupAddress(Address previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Customers, this))
            {
                previousValue.Customers = null;
            }
    
            if (Address != null)
            {
                Address.Customers = this;
            }
        }

        #endregion

    }
}
