//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using JetCoders.Shared;

namespace Connections
{
    [Serializable]
    public partial class FinancialYearMaster : IEntityBase
    {
        #region Primitive Properties
    
        public virtual int FinancialYearMasterId
        {
            get;
            set;
        }
    
        public virtual string YearCode
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateFrom
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateTo
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsCancelled
        {
            get;
            set;
        }
    
        public virtual System.DateTime AccessedDate
        {
            get;
            set;
        }
    
        public virtual int AccessedBy
        {
            get;
            set;
        }

        #endregion

    }
}
