//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using JetCoders.Shared;

namespace Connections
{
    [Serializable]
    public partial class FirmMaster : IEntityBase
    {
        #region Primitive Properties
    
        public virtual int FirmMasterId
        {
            get;
            set;
        }
    
        public virtual string FirmName
        {
            get;
            set;
        }
    
        public virtual string FirmEmail
        {
            get;
            set;
        }
    
        public virtual string FirmTopHeader
        {
            get;
            set;
        }
    
        public virtual string FirmHeader
        {
            get;
            set;
        }
    
        public virtual string FirmWebsite
        {
            get;
            set;
        }
    
        public virtual byte[] FirmLogo
        {
            get;
            set;
        }
    
        public virtual string FirmVATNumber
        {
            get;
            set;
        }
    
        public virtual string FirmTINNumber
        {
            get;
            set;
        }
    
        public virtual string FirmAddress
        {
            get;
            set;
        }
    
        public virtual string FirmAdditionalInfo
        {
            get;
            set;
        }
    
        public virtual decimal Tax
        {
            get;
            set;
        }
    
        public virtual decimal OtherTax
        {
            get;
            set;
        }
    
        public virtual System.DateTime AccessedDate
        {
            get;
            set;
        }
    
        public virtual int AccessedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> SyncCatalogData
        {
            get { return _syncCatalogData; }
            set { _syncCatalogData = value; }
        }
        private Nullable<bool> _syncCatalogData = false;

        #endregion

    }
}
