//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Connections.Entities
{
    public partial class inventoryContainer : ObjectContext,  IinventoryContainer
    {
        public const string ConnectionString = "name=inventoryContainer";
        public const string ContainerName = "inventoryContainer";
    
        #region Constructors
    
        public inventoryContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public inventoryContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public inventoryContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public IObjectSet<Address> Addresses
        {
            get { return _addresses  ?? (_addresses = CreateObjectSet<Address>("Addresses")); }
        }
        private ObjectSet<Address> _addresses;
    
        public IObjectSet<Customer> Customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<Customer>("Customers")); }
        }
        private ObjectSet<Customer> _customers;
    
        public IObjectSet<LoginInformation> LoginInformations
        {
            get { return _loginInformations  ?? (_loginInformations = CreateObjectSet<LoginInformation>("LoginInformations")); }
        }
        private ObjectSet<LoginInformation> _loginInformations;
    
        public IObjectSet<Supplier> Suppliers
        {
            get { return _suppliers  ?? (_suppliers = CreateObjectSet<Supplier>("Suppliers")); }
        }
        private ObjectSet<Supplier> _suppliers;
    
        public IObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public IObjectSet<ProductMaster> ProductMasters
        {
            get { return _productMasters  ?? (_productMasters = CreateObjectSet<ProductMaster>("ProductMasters")); }
        }
        private ObjectSet<ProductMaster> _productMasters;
    
        public IObjectSet<ConfigurationMaster> ConfigurationMasters
        {
            get { return _configurationMasters  ?? (_configurationMasters = CreateObjectSet<ConfigurationMaster>("ConfigurationMasters")); }
        }
        private ObjectSet<ConfigurationMaster> _configurationMasters;
    
        public IObjectSet<JewelTransaction> JewelTransactions
        {
            get { return _jewelTransactions  ?? (_jewelTransactions = CreateObjectSet<JewelTransaction>("JewelTransactions")); }
        }
        private ObjectSet<JewelTransaction> _jewelTransactions;
    
        public IObjectSet<CostingDetail> CostingDetails
        {
            get { return _costingDetails  ?? (_costingDetails = CreateObjectSet<CostingDetail>("CostingDetails")); }
        }
        private ObjectSet<CostingDetail> _costingDetails;
    
        public IObjectSet<JewelStockLedger> JewelStockLedgers
        {
            get { return _jewelStockLedgers  ?? (_jewelStockLedgers = CreateObjectSet<JewelStockLedger>("JewelStockLedgers")); }
        }
        private ObjectSet<JewelStockLedger> _jewelStockLedgers;
    
        public IObjectSet<FinancialYearMaster> FinancialYearMasters
        {
            get { return _financialYearMasters  ?? (_financialYearMasters = CreateObjectSet<FinancialYearMaster>("FinancialYearMasters")); }
        }
        private ObjectSet<FinancialYearMaster> _financialYearMasters;
    
        public IObjectSet<TransactionLookup> TransactionLookups
        {
            get { return _transactionLookups  ?? (_transactionLookups = CreateObjectSet<TransactionLookup>("TransactionLookups")); }
        }
        private ObjectSet<TransactionLookup> _transactionLookups;
    
        public IObjectSet<JewelMaster> JewelMasters
        {
            get { return _jewelMasters  ?? (_jewelMasters = CreateObjectSet<JewelMaster>("JewelMasters")); }
        }
        private ObjectSet<JewelMaster> _jewelMasters;
    
        public IObjectSet<TraceLog> TraceLogs
        {
            get { return _traceLogs  ?? (_traceLogs = CreateObjectSet<TraceLog>("TraceLogs")); }
        }
        private ObjectSet<TraceLog> _traceLogs;
    
        public IObjectSet<LooseDiamondTransaction> LooseDiamondTransactions
        {
            get { return _looseDiamondTransactions  ?? (_looseDiamondTransactions = CreateObjectSet<LooseDiamondTransaction>("LooseDiamondTransactions")); }
        }
        private ObjectSet<LooseDiamondTransaction> _looseDiamondTransactions;
    
        public IObjectSet<TransactionInvoices> TransactionInvoices
        {
            get { return _transactionInvoices  ?? (_transactionInvoices = CreateObjectSet<TransactionInvoices>("TransactionInvoices")); }
        }
        private ObjectSet<TransactionInvoices> _transactionInvoices;
    
        public IObjectSet<AccountLedger> AccountLedgers
        {
            get { return _accountLedgers  ?? (_accountLedgers = CreateObjectSet<AccountLedger>("AccountLedgers")); }
        }
        private ObjectSet<AccountLedger> _accountLedgers;
    
        public IObjectSet<FirmMaster> FirmMasters
        {
            get { return _firmMasters  ?? (_firmMasters = CreateObjectSet<FirmMaster>("FirmMasters")); }
        }
        private ObjectSet<FirmMaster> _firmMasters;
    
        public IObjectSet<CreditNote> CreditNotes
        {
            get { return _creditNotes  ?? (_creditNotes = CreateObjectSet<CreditNote>("CreditNotes")); }
        }
        private ObjectSet<CreditNote> _creditNotes;
    
        public IObjectSet<LooseDiamondLookup> LooseDiamondLookups
        {
            get { return _looseDiamondLookups  ?? (_looseDiamondLookups = CreateObjectSet<LooseDiamondLookup>("LooseDiamondLookups")); }
        }
        private ObjectSet<LooseDiamondLookup> _looseDiamondLookups;

        #endregion

    
    	public bool HasPendingChanges()
    	{
    		System.Data.EntityState state = System.Data.EntityState.Added | System.Data.EntityState.Detached | System.Data.EntityState.Modified;
    		foreach (var i in ObjectStateManager.GetObjectStateEntries(state))
    			return true;
    
    		return false;
    	}
    
    }
    
    public interface IinventoryContainer
    {
    	int SaveChanges();
    	bool HasPendingChanges();
    	IObjectSet<Address> Addresses { get; }
    	IObjectSet<Customer> Customers { get; }
    	IObjectSet<LoginInformation> LoginInformations { get; }
    	IObjectSet<Supplier> Suppliers { get; }
    	IObjectSet<User> Users { get; }
    	IObjectSet<ProductMaster> ProductMasters { get; }
    	IObjectSet<ConfigurationMaster> ConfigurationMasters { get; }
    	IObjectSet<JewelTransaction> JewelTransactions { get; }
    	IObjectSet<CostingDetail> CostingDetails { get; }
    	IObjectSet<JewelStockLedger> JewelStockLedgers { get; }
    	IObjectSet<FinancialYearMaster> FinancialYearMasters { get; }
    	IObjectSet<TransactionLookup> TransactionLookups { get; }
    	IObjectSet<JewelMaster> JewelMasters { get; }
    	IObjectSet<TraceLog> TraceLogs { get; }
    	IObjectSet<LooseDiamondTransaction> LooseDiamondTransactions { get; }
    	IObjectSet<TransactionInvoices> TransactionInvoices { get; }
    	IObjectSet<AccountLedger> AccountLedgers { get; }
    	IObjectSet<FirmMaster> FirmMasters { get; }
    	IObjectSet<CreditNote> CreditNotes { get; }
    	IObjectSet<LooseDiamondLookup> LooseDiamondLookups { get; }
    }
}
