//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using JetCoders.Shared;

namespace Connections
{
    [Serializable]
    public partial class JewelStockLedger : IEntityBase
    {
        #region Primitive Properties
    
        public virtual int JewelStockMasterId
        {
            get;
            set;
        }
    
        public virtual string JewelNumber
        {
            get;
            set;
        }
    
        public virtual System.DateTime TransactionDate
        {
            get;
            set;
        }
    
        public virtual string DesignCode
        {
            get;
            set;
        }
    
    	public JewelItemCategory JewelItemCategory
    	{
    		get { return (JewelItemCategory) JewelItemCategory_Enum; }
    		set { JewelItemCategory_Enum = (short) value; }
    	}
        public virtual short JewelItemCategory_Enum
        {
            get;
            set;
        }
    
        public virtual string JewelType
        {
            get;
            set;
        }
    
        public virtual decimal MetalWeight
        {
            get;
            set;
        }
    
        public virtual string MetalColor
        {
            get;
            set;
        }
    
    	public JewelState JewelState
    	{
    		get { return (JewelState) JewelState_Enum; }
    		set { JewelState_Enum = (short) value; }
    	}
        public virtual short JewelState_Enum
        {
            get;
            set;
        }
    
        public virtual decimal StoneWeight
        {
            get;
            set;
        }
    
        public virtual int StonePcs
        {
            get;
            set;
        }
    
        public virtual decimal CStoneWeight
        {
            get;
            set;
        }
    
        public virtual int CStonePcs
        {
            get;
            set;
        }
    
        public virtual string KT
        {
            get;
            set;
        }
    
        public virtual decimal TotalWeight
        {
            get;
            set;
        }
    
        public virtual string CertificateNumber
        {
            get;
            set;
        }
    
    	public StockStatus StockStatus
    	{
    		get { return (StockStatus) StockStatus_Enum; }
    		set { StockStatus_Enum = (short) value; }
    	}
        public virtual short StockStatus_Enum
        {
            get;
            set;
        }
    
        public virtual System.DateTime AccessedDate
        {
            get;
            set;
        }
    
        public virtual int AccessedBy
        {
            get;
            set;
        }

        #endregion

    }
}
