//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using JetCoders.Shared;

namespace Connections
{
    [Serializable]
    public partial class JewelMaster : IEntityBase
    {
        #region Primitive Properties
    
        public virtual int JewelId
        {
            get;
            set;
        }
    
        public virtual string JewelNo
        {
            get;
            set;
        }
    
        public virtual string StyleNo
        {
            get;
            set;
        }
    
        public virtual string JewelDescription
        {
            get;
            set;
        }
    
        public virtual string MetalColor
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DiamondPcs
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> DiamondWt
        {
            get;
            set;
        }
    
        public virtual decimal CStoneWeight
        {
            get;
            set;
        }
    
        public virtual int CStonePcs
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> GrsWt
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> NetWt
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AccessedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> AccessedBy
        {
            get;
            set;
        }
    
        public virtual bool Active
        {
            get;
            set;
        }

        #endregion

    }
}
