//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using JetCoders.Shared;

namespace Connections
{
    [Serializable]
    public partial class TraceLog : IEntityBase
    {
        #region Primitive Properties
    
        public virtual System.Guid TraceLogId
        {
            get;
            set;
        }
    
        public virtual System.DateTime TraceLogDate
        {
            get;
            set;
        }
    
        public virtual string LogGuid
        {
            get;
            set;
        }
    
        public virtual string LogDateTime
        {
            get;
            set;
        }
    
        public virtual string Level
        {
            get;
            set;
        }
    
        public virtual string MachineName
        {
            get;
            set;
        }
    
        public virtual string Class
        {
            get;
            set;
        }
    
        public virtual string Message
        {
            get;
            set;
        }
    
        public virtual string Exception
        {
            get;
            set;
        }
    
        public virtual Nullable<long> GCTotalMemory
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GCGen0Count
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GCGen1Count
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GCGen2Count
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GCMaxGen
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ProcessId
        {
            get;
            set;
        }
    
        public virtual string Identity
        {
            get;
            set;
        }

        #endregion

    }
}
