//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using JetCoders.Shared;

namespace Connections
{
    [Serializable]
    public partial class TransactionInvoices : IEntityBase
    {
        #region Primitive Properties
    
        public virtual int TransactionInvoiceId
        {
            get;
            set;
        }
    
        public virtual string InvoiceNumber
        {
            get;
            set;
        }
    
        public virtual System.DateTime InvoiceDate
        {
            get;
            set;
        }
    
        public virtual decimal NetAmount
        {
            get;
            set;
        }
    
        public virtual decimal OtherCharges
        {
            get;
            set;
        }
    
        public virtual decimal Tax
        {
            get;
            set;
        }
    
        public virtual string TransactionPartyRef
        {
            get;
            set;
        }
    
        public virtual string Remarks
        {
            get;
            set;
        }
    
        public virtual string PaymentTerm
        {
            get;
            set;
        }
    
        public virtual System.DateTime AccessedDate
        {
            get;
            set;
        }
    
        public virtual int AccessedBy
        {
            get;
            set;
        }
    
        public virtual bool Cancelled
        {
            get;
            set;
        }

        #endregion

    }
}
