//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using JetCoders.Shared;

namespace Connections
{
    [Serializable]
    public partial class User : IEntityBase
    {
        #region Primitive Properties
    
        public virtual int UserId
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
    	public UserStatus UserStatus
    	{
    		get { return (UserStatus) UserStatus_Enum; }
    		set { UserStatus_Enum = (short) value; }
    	}
        public virtual short UserStatus_Enum
        {
            get;
            set;
        }
    
    
    	private UserProperties _properties = null;
    	
    	public virtual UserProperties Properties
    	{
    		get 
    		{
    			if ( _properties == null )
    				_properties = new UserProperties();
    				
    			return _properties;
    		}
    		
    		set { _properties = value; }
    	}
        private string UserProperties_Xml
        {
    		get { return this.Properties.Serialize<UserProperties>().ToString(); }
    		set { this.Properties = DataContractHelper.Deserialize<UserProperties>(value); }
        }
    
        public virtual Nullable<int> UserImageId
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastLoginDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime AccessedDate
        {
            get;
            set;
        }
    
        public virtual int AccessedBy
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual LoginInformation LoginInformations
        {
            get { return _loginInformations; }
            set
            {
                if (!ReferenceEquals(_loginInformations, value))
                {
                    var previousValue = _loginInformations;
                    _loginInformations = value;
                    FixupLoginInformations(previousValue);
                }
            }
        }
        private LoginInformation _loginInformations;
    
        public virtual Address Address
        {
            get { return _address; }
            set
            {
                if (!ReferenceEquals(_address, value))
                {
                    var previousValue = _address;
                    _address = value;
                    FixupAddress(previousValue);
                }
            }
        }
        private Address _address;

        #endregion

        #region Association Fixup
    
        private void FixupLoginInformations(LoginInformation previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.User, this))
            {
                previousValue.User = null;
            }
    
            if (LoginInformations != null)
            {
                LoginInformations.User = this;
            }
        }
    
        private void FixupAddress(Address previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Users, this))
            {
                previousValue.Users = null;
            }
    
            if (Address != null)
            {
                Address.Users = this;
            }
        }

        #endregion

    }
}
