//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelInventory.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JewelInventory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _lock {
            get {
                object obj = ResourceManager.GetObject("_lock", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap applications {
            get {
                object obj = ResourceManager.GetObject("applications", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for Thumbnails.
        /// </summary>
        public static string BaseFormControl_CellMouseMove_Click_here_for_Thumbnails {
            get {
                return ResourceManager.GetString("BaseFormControl_CellMouseMove_Click_here_for_Thumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to cancel order?.
        /// </summary>
        public static string BaseFormControl_CloseOrderForm_Are_you_sure_want_to_cancel_order_ {
            get {
                return ResourceManager.GetString("BaseFormControl_CloseOrderForm_Are_you_sure_want_to_cancel_order_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap calendar_date {
            get {
                object obj = ResourceManager.GetObject("calendar_date", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap computers {
            get {
                object obj = ResourceManager.GetObject("computers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dialogueHeaderCenter {
            get {
                object obj = ResourceManager.GetObject("dialogueHeaderCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap filesave {
            get {
                object obj = ResourceManager.GetObject("filesave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select costing category.
        /// </summary>
        public static string frmConfiguration_btnSave_Click_Please_select_costing_category {
            get {
                return ResourceManager.GetString("frmConfiguration_btnSave_Click_Please_select_costing_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to server failed..
        /// </summary>
        public static string frmConnection_btnConnect_Click_Connection_to_server_failed_ {
            get {
                return ResourceManager.GetString("frmConnection_btnConnect_Click_Connection_to_server_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to server succeeded..
        /// </summary>
        public static string frmConnection_btnConnect_Click_Connection_to_server_succeeded_ {
            get {
                return ResourceManager.GetString("frmConnection_btnConnect_Click_Connection_to_server_succeeded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to server succeeded, Please restart your application..
        /// </summary>
        public static string frmConnection_btnConnect_Click_Connection_to_server_succeeded__Please_restart_your_application_ {
            get {
                return ResourceManager.GetString("frmConnection_btnConnect_Click_Connection_to_server_succeeded__Please_restart_you" +
                        "r_application_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        Costing Rates .
        /// </summary>
        public static string frmCostingBase_frmCostingBase_Load________Costing_Rates_ {
            get {
                return ResourceManager.GetString("frmCostingBase_frmCostingBase_Load________Costing_Rates_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete information provided..
        /// </summary>
        public static string frmCostingBase_TryParseCostingData_Incomplete_information_provided_ {
            get {
                return ResourceManager.GetString("frmCostingBase_TryParseCostingData_Incomplete_information_provided_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No costing details found. Please fill costing chart completly..
        /// </summary>
        public static string frmCostingBase_TryParseCostingData_No_costing_details_found__Please_fill_costing_chart_completly_ {
            get {
                return ResourceManager.GetString("frmCostingBase_TryParseCostingData_No_costing_details_found__Please_fill_costing_" +
                        "chart_completly_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stamping charges is invalid..
        /// </summary>
        public static string frmCostingBase_TryParseCostingData_The_stamping_charges_is_invalid_ {
            get {
                return ResourceManager.GetString("frmCostingBase_TryParseCostingData_The_stamping_charges_is_invalid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Data Saved Successfuly.
        /// </summary>
        public static string frmCostingConfirmation_frmContingConfirmation_Load__Data_Saved_Successfuly {
            get {
                return ResourceManager.GetString("frmCostingConfirmation_frmContingConfirmation_Load__Data_Saved_Successfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete information provided..
        /// </summary>
        public static string frmCostingRates_OnAddtoListClick_Incomplete_information_provided_ {
            get {
                return ResourceManager.GetString("frmCostingRates_OnAddtoListClick_Incomplete_information_provided_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to clear out all records..
        /// </summary>
        public static string frmCostingRates_OnClearAllItemsClick_Are_you_sure_want_to_clear_out_all_records_ {
            get {
                return ResourceManager.GetString("frmCostingRates_OnClearAllItemsClick_Are_you_sure_want_to_clear_out_all_records_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current form details will be cleared out, Are you sure want to go back ?.
        /// </summary>
        public static string frmCostingRates_OnPrevClick_Your_current_form_details_will_be_cleared_out__Are_you_sure_want_to_go_back__ {
            get {
                return ResourceManager.GetString("frmCostingRates_OnPrevClick_Your_current_form_details_will_be_cleared_out__Are_yo" +
                        "u_sure_want_to_go_back__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete information provided..
        /// </summary>
        public static string frmCostingRates_onSaveClick_Incomplete_information_provided_ {
            get {
                return ResourceManager.GetString("frmCostingRates_onSaveClick_Incomplete_information_provided_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email Address..
        /// </summary>
        public static string frmCustomerDataEntry_btnSave_Click_Please_Enter_Valid_Email_Address_ {
            get {
                return ResourceManager.GetString("frmCustomerDataEntry_btnSave_Click_Please_Enter_Valid_Email_Address_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved!.
        /// </summary>
        public static string frmCustomerDataEntry_btnSave_Click_Record_saved_ {
            get {
                return ResourceManager.GetString("frmCustomerDataEntry_btnSave_Click_Record_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Exit?.
        /// </summary>
        public static string frmDataEntry_frmDataEntry_FormClosing_Are_you_sure_you_want_to_Exit_ {
            get {
                return ResourceManager.GetString("frmDataEntry_frmDataEntry_FormClosing_Are_you_sure_you_want_to_Exit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t saved your data..
        /// </summary>
        public static string frmDataEntry_frmDataEntry_FormClosing_You_haven_t_saved_your_data_ {
            get {
                return ResourceManager.GetString("frmDataEntry_frmDataEntry_FormClosing_You_haven_t_saved_your_data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current form details will be cleared out, Are you sure want to go back ?.
        /// </summary>
        public static string frmExcelCostingRates_OnPrevClick_Your_current_form_details_will_be_cleared_out__Are_you_sure_want_to_go_back__ {
            get {
                return ResourceManager.GetString("frmExcelCostingRates_OnPrevClick_Your_current_form_details_will_be_cleared_out__A" +
                        "re_you_sure_want_to_go_back__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =====================================.
        /// </summary>
        public static string frmExcelCostingRates_openFileDialog1_FileOk_ {
            get {
                return ResourceManager.GetString("frmExcelCostingRates_openFileDialog1_FileOk_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following error(s) occoured while processing your excel.
        /// </summary>
        public static string frmExcelCostingRates_openFileDialog1_FileOk_Following_error_s__occoured_while_processing_your_excel {
            get {
                return ResourceManager.GetString("frmExcelCostingRates_openFileDialog1_FileOk_Following_error_s__occoured_while_pro" +
                        "cessing_your_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure excel file is numbered correctly..
        /// </summary>
        public static string frmExcelCostingRates_openFileDialog1_FileOk_Please_ensure_excel_file_is_numbered_correctly_ {
            get {
                return ResourceManager.GetString("frmExcelCostingRates_openFileDialog1_FileOk_Please_ensure_excel_file_is_numbered_" +
                        "correctly_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling financial year record can not be undone.
        ///if you have done any transaction and choosing for cancellation, transaction might be in inconsistance state, please consult your vendor. 
        ///
        ///Are you sure want to cancel financial record ?.
        /// </summary>
        public static string frmFinancialYear_btnSave_Click_ {
            get {
                return ResourceManager.GetString("frmFinancialYear_btnSave_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved!.
        /// </summary>
        public static string frmFinancialYear_btnSave_Click_Record_saved_ {
            get {
                return ResourceManager.GetString("frmFinancialYear_btnSave_Click_Record_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file Logo path..
        /// </summary>
        public static string frmFirmMaster_btnSave_Click_Invalid_file_Logo_path_ {
            get {
                return ResourceManager.GetString("frmFirmMaster_btnSave_Click_Invalid_file_Logo_path_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Other TAX field.
        /// </summary>
        public static string frmFirmMaster_btnSave_Click_Invalid_Other_TAX_field {
            get {
                return ResourceManager.GetString("frmFirmMaster_btnSave_Click_Invalid_Other_TAX_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TAX field.
        /// </summary>
        public static string frmFirmMaster_btnSave_Click_Invalid_TAX_field {
            get {
                return ResourceManager.GetString("frmFirmMaster_btnSave_Click_Invalid_TAX_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email Address..
        /// </summary>
        public static string frmFirmMaster_btnSave_Click_Please_Enter_Valid_Email_Address_ {
            get {
                return ResourceManager.GetString("frmFirmMaster_btnSave_Click_Please_Enter_Valid_Email_Address_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transaction found..
        /// </summary>
        public static string frmJewelHistory_btnShowHistory_Click_No_transaction_found_ {
            get {
                return ResourceManager.GetString("frmJewelHistory_btnShowHistory_Click_No_transaction_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter jewelnumber or design code..
        /// </summary>
        public static string frmJewelHistory_btnShowHistory_Click_Please_enter_jewelnumber_or_design_code_ {
            get {
                return ResourceManager.GetString("frmJewelHistory_btnShowHistory_Click_Please_enter_jewelnumber_or_design_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data found!.
        /// </summary>
        public static string frmJewelTransactionsReport_GetJewelTransactionReport_No_Data_found_ {
            get {
                return ResourceManager.GetString("frmJewelTransactionsReport_GetJewelTransactionReport_No_Data_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string frmLogin_btnLOGIN_Click_Invalid_username_or_password {
            get {
                return ResourceManager.GetString("frmLogin_btnLOGIN_Click_Invalid_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved!.
        /// </summary>
        public static string frmLooseDiamonds_btnSave_Click_Record_saved_ {
            get {
                return ResourceManager.GetString("frmLooseDiamonds_btnSave_Click_Record_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select transaction.
        /// </summary>
        public static string frmManageTransaction_btnGo_Click_Please_select_transaction {
            get {
                return ResourceManager.GetString("frmManageTransaction_btnGo_Click_Please_select_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to return stock into account.
        /// </summary>
        public static string frmManageTransaction_lnkRTS_LinkClicked_Are_you_sure_want_to_return_stock_into_account {
            get {
                return ResourceManager.GetString("frmManageTransaction_lnkRTS_LinkClicked_Are_you_sure_want_to_return_stock_into_ac" +
                        "count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no item available to be returned..
        /// </summary>
        public static string frmManageTransaction_lnkRTS_LinkClicked_no_item_available_to_be_returned_ {
            get {
                return ResourceManager.GetString("frmManageTransaction_lnkRTS_LinkClicked_no_item_available_to_be_returned_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Stock.
        /// </summary>
        public static string frmManageTransaction_lnkRTS_LinkClicked_Return_To_Stock {
            get {
                return ResourceManager.GetString("frmManageTransaction_lnkRTS_LinkClicked_Return_To_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email Address..
        /// </summary>
        public static string frmManageUser_btnSave_Click_Please_Enter_Valid_Email_Address_ {
            get {
                return ResourceManager.GetString("frmManageUser_btnSave_Click_Please_Enter_Valid_Email_Address_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved!.
        /// </summary>
        public static string frmManageUser_btnSave_Click_Record_saved_ {
            get {
                return ResourceManager.GetString("frmManageUser_btnSave_Click_Record_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewel data updated successfully,
        ///Please go to manage transaction to print new tag..
        /// </summary>
        public static string frmMasterMaintenance_btnSave_Click_ {
            get {
                return ResourceManager.GetString("frmMasterMaintenance_btnSave_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to exit ?.
        /// </summary>
        public static string frmMDIParent__terminate_Are_you_sure_want_to_exit__ {
            get {
                return ResourceManager.GetString("frmMDIParent__terminate_Are_you_sure_want_to_exit__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string frmMDIParent__terminate_Exit_Application {
            get {
                return ResourceManager.GetString("frmMDIParent__terminate_Exit_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to close current application.
        /// </summary>
        public static string frmMDIParent_backupToolStripMenuItem_Click_Are_you_sure_want_to_close_current_application {
            get {
                return ResourceManager.GetString("frmMDIParent_backupToolStripMenuItem_Click_Are_you_sure_want_to_close_current_app" +
                        "lication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial year is not set for current date, please create financial year, 
        ///Click OK to create Financial year..
        /// </summary>
        public static string frmMDIParent_CheckUserAccess_ {
            get {
                return ResourceManager.GetString("frmMDIParent_CheckUserAccess_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Directory path not set !, please set it from Tools -&gt; App Settings !.
        /// </summary>
        public static string frmMDIParent_frmMDIParent_Load_Image_Directory_path_not_set____please_set_it_from_Tools____App_Settings__ {
            get {
                return ResourceManager.GetString("frmMDIParent_frmMDIParent_Load_Image_Directory_path_not_set____please_set_it_from" +
                        "_Tools____App_Settings__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  already exists! Please search for new record .
        /// </summary>
        public static string frmMemoOrder_FindJewelByJewelNo__already_exists__Please_search_for_new_record_ {
            get {
                return ResourceManager.GetString("frmMemoOrder_FindJewelByJewelNo__already_exists__Please_search_for_new_record_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Not found !.
        /// </summary>
        public static string frmMemoOrder_FindJewelByJewelNo_Records_Not_found__ {
            get {
                return ResourceManager.GetString("frmMemoOrder_FindJewelByJewelNo_Records_Not_found__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select record to create memo !.
        /// </summary>
        public static string frmMemoOrder_onbtnNextClick_Please_select_record_to_create_memo__ {
            get {
                return ResourceManager.GetString("frmMemoOrder_onbtnNextClick_Please_select_record_to_create_memo__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stamping charges is invalid..
        /// </summary>
        public static string frmMemoOrder_VALIDATEDATAGRID_The_stamping_charges_is_invalid_ {
            get {
                return ResourceManager.GetString("frmMemoOrder_VALIDATEDATAGRID_The_stamping_charges_is_invalid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct transaction date..
        /// </summary>
        public static string frmPartyTransaction_btnShowTransactions_Click_Please_correct_transaction_date_ {
            get {
                return ResourceManager.GetString("frmPartyTransaction_btnShowTransactions_Click_Please_correct_transaction_date_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transaction found for this period..
        /// </summary>
        public static string frmPartyTransaction_FindTransaction_No_transaction_found_for_this_period_ {
            get {
                return ResourceManager.GetString("frmPartyTransaction_FindTransaction_No_transaction_found_for_this_period_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select jewels..
        /// </summary>
        public static string frmSalesOrder_OnbtnSaveClick_Please_select_jewels_ {
            get {
                return ResourceManager.GetString("frmSalesOrder_OnbtnSaveClick_Please_select_jewels_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Added Successfully.
        /// </summary>
        public static string frmSalesOrder_OnbtnSaveClick_Records_Added_Successfully {
            get {
                return ResourceManager.GetString("frmSalesOrder_OnbtnSaveClick_Records_Added_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Folder Path Not Found.
        /// </summary>
        public static string frmSettings_btnSave_Click_Error___Folder_Path_Not_Found {
            get {
                return ResourceManager.GetString("frmSettings_btnSave_Click_Error___Folder_Path_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Directory path not set !, please set it from Tools -&gt; App Settings !.
        /// </summary>
        public static string frmSettings_btnSave_Click_Image_Directory_path_not_set____please_set_it_from_Tools____App_Settings__ {
            get {
                return ResourceManager.GetString("frmSettings_btnSave_Click_Image_Directory_path_not_set____please_set_it_from_Tool" +
                        "s____App_Settings__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter proper folder path.
        /// </summary>
        public static string frmSettings_btnSave_Click_Please_enter_proper_folder_path {
            get {
                return ResourceManager.GetString("frmSettings_btnSave_Click_Please_enter_proper_folder_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting are Saved.
        /// </summary>
        public static string frmSettings_btnSave_Click_Setting_are_Saved {
            get {
                return ResourceManager.GetString("frmSettings_btnSave_Click_Setting_are_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email Address..
        /// </summary>
        public static string frmSupplierDataEntry_btnSave_Click_Please_Enter_Valid_Email_Address_ {
            get {
                return ResourceManager.GetString("frmSupplierDataEntry_btnSave_Click_Please_Enter_Valid_Email_Address_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved!.
        /// </summary>
        public static string frmSupplierDataEntry_btnSave_Click_Record_saved_ {
            get {
                return ResourceManager.GetString("frmSupplierDataEntry_btnSave_Click_Record_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help1 {
            get {
                object obj = ResourceManager.GetObject("help1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your software demo period is over, Please contact vendor.
        /// </summary>
        public static string Program_Main_Your_software_demo_period_is_over__Please_contact_vendor {
            get {
                return ResourceManager.GetString("Program_Main_Your_software_demo_period_is_over__Please_contact_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TirthJewels {
            get {
                object obj = ResourceManager.GetObject("TirthJewels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
